export enum SocketEvent {
  RUN_LOG = 'run:log',
  TASK_STARTED = 'task:started',
  TASK_COMPLETED = 'task:completed',
  DEP_OPERATE = 'dep:operate',
  MESSAGE_NEW = 'message:new',
  UPDATE_REFRESH = 'update:refresh',
  DAEMON_LOG_SUBSCRIBE = 'daemon:log:subscribe',
  DAEMON_LOG_UNSUBSCRIBE = 'daemon:log:unsubscribe',
  DAEMON_LOG_DATA = 'daemon:log:data',
  TERMINAL_SPAWN = 'terminal:spawn',
  TERMINAL_INPUT = 'terminal:input',
  TERMINAL_RESIZE = 'terminal:resize',
  TERMINAL_READY = 'terminal:ready',
  TERMINAL_OUTPUT = 'terminal:output',
  TERMINAL_EXIT = 'terminal:exit',
  TERMINAL_ERROR = 'terminal:error',
}
