blank_issues_enabled: false
contact_links:
  - name: Create new issue
    url: https://arcadia-issue-helper.netlify.app/
    about: The issue which is not created via Issue Helper will be closed immediately.