<template>
  <NCard class="card" hoverable>
    <n-form ref="formRef" :model="form" label-width="auto" :rules="rules" label-position="top" size="large" class="form">
      <n-grid cols="8" :x-gap="16">
        <!-- Issue 标题 -->
        <n-form-item-gi :label="contentText.issueTitleHint" path="title" :span="5">
          <n-input v-model:value="form.title" clearable />
        </n-form-item-gi>

        <!-- Issue 类别 -->
        <n-form-item-gi :label="contentText.issueTypesHint" path="type" :span="3">
          <n-radio-group v-model:value="form.type" style="width: 100%; text-align: center">
            <n-radio-button style="width: calc(50% - 1px)" :value="issueTypeOptions[0].value">
              {{ issueTypeOptions[0].label }}
            </n-radio-button>
            <n-radio-button style="width: 50%" :value="issueTypeOptions[1].value">
              {{ issueTypeOptions[1].label }}
            </n-radio-button>
          </n-radio-group>
        </n-form-item-gi>
      </n-grid>

      <template v-if="isBug">

        <n-alert type="default" closable :show-icon="false" class="m-b-24">
          <span class="alert-font">{{ contentText.firstTip }}</span>
        </n-alert>

        <n-grid cols="2" :x-gap="16">
          <!-- 运行环境 -->
          <n-form-item-gi :label="contentText.systemPlatformHint" path="systemPlatform">
            <n-select v-model:value="form.systemPlatform" clearable :options="system.platform" />
          </n-form-item-gi>
          <!-- 系统架构 -->
          <n-form-item-gi :label="contentText.systemArchHint" path="systemArch">
            <n-select v-model:value="form.systemArch" clearable :options="system.arch" />
          </n-form-item-gi>
        </n-grid>

        <!-- 期望的结果是什么 -->
        <n-form-item :label="contentText.expectHint" path="expected">
          <n-input v-model:value="form.expected" type="textarea" :autosize="autosizeConfig" />
        </n-form-item>

        <!-- 实际的结果是什么 -->
        <n-form-item :label="contentText.actualHint" path="actual">
          <n-input v-model:value="form.actual" type="textarea" :autosize="autosizeConfig" />
        </n-form-item>

        <!-- 补充说明（可选） -->
        <n-form-item :label="contentText.remarks">
          <n-input v-model:value="form.remarks" type="textarea" :autosize="autosizeConfig" :placeholder="contentText.remarksTips" />
        </n-form-item>
      </template>

      <template v-else>
        <!-- 这个功能解决了什么问题 -->
        <n-form-item :label="contentText.functionContent" path="functionContent">
          <n-input v-model:value="form.functionContent" type="textarea" :autosize="autosizeConfig" clearable />
        </n-form-item>
        <n-alert type="default" :show-icon="false" class="m-b-24">
          <span class="alert-font">{{ contentText.functionContentTip }}</span>
        </n-alert>
      </template>

      <n-form-item class="preview" :show-feedback="false">
        <n-button strong block type="primary" :focusable="false" @click="handlePreview()">
          {{ contentText.preview }}
        </n-button>
      </n-form-item>
    </n-form>
  </NCard>

  <n-modal v-model:show="previewVisible" :auto-focus="false">
    <n-card :title="contentText.dialog.title" closable @close="previewVisible = false" class="modal-card">
      <div class="preview-content">
        <v-node :render="issueVNode" />
      </div>
      <div class="preview-footer">
        <NButton strong block type="primary" :focusable="false" @click="create()">
          {{ contentText.dialog.button }}
        </NButton>
      </div>
    </n-card>
  </n-modal>
</template>

<script lang="ts">
import { NAlert, NH3 } from 'naive-ui'
import { VNodeChild } from 'vue'
import content from '../content.js'
import { IssueTypeLabel } from '../interface'

function createComment (type) {
  const comment = '<!-- generated by issue-helper DO NOT REMOVE -->'
  return comment.replace('-->', IssueTypeLabel[type] + ' -->')
}

export default defineComponent({
  name: 'IssueForm',
  props: {
    lang: {
      type: String as PropType<'en-US' | 'zh-CN'>,
    },
  },
  setup: (props) => {
    const lang = toRef(props, 'lang')
    const message = useMessage()
    const contentText = computed(() => content[lang.value])
    const issueTypeOptions = computed(() => contentText.value.issueTypes)
    const formRef: Ref<any> = ref(null)
    const archOptions = computed(() => ([
      {
        label: 'x86_64',
        value: 'x86_64',
      },
      {
        label: 'aarch64',
        value: 'aarch64',
      },
      {
        label: 'armv7l',
        value: 'armv7l',
      },
    ]))
    const platformOptions = computed(() => ([
      {
        label: contentText.value.systemSelectItemPC,
        value: 'PC / Server / VPS',
      },
      {
        label: contentText.value.systemSelectItemDockerPlugin,
        value: 'Router / NAS',
      },
      {
        label: 'Docker Desktop',
        value: 'Docker Desktop',
      },
      {
        label: contentText.value.systemSelectItemOther,
        value: 'Other',
      },
    ]))
    const formData = reactive({
      form: {
        repo: 'SuperManito/Arcadia',
        title: '',
        type: 'Bug',
        systemArch: null,
        systemPlatform: null,
        expected: '',
        actual: '',
        remarks: '',
        functionContent: '',
      },
      system: {
        arch: archOptions,
        platform: platformOptions,
      },
    })
    const issue = ref('')
    const issueRenderRef: Ref<(() => VNodeChild) | null> = ref(null)
    const tipVisible: Ref<boolean> = ref(false)
    const previewVisible: Ref<boolean> = ref(false)

    const isBug = computed(() => formData.form.type === 'Bug')

    const rules = computed(() => {
      const valid = contentText.value.valid
      const rules: any = {}
      for (const prop in valid) {
        if (prop === 'remarks') {
          continue
        }
        rules[prop] = [
          {
            required: true,
            message: valid[prop],
            trigger: ['blur', 'change', 'input'],
          },
        ]
      }
      return rules
    })

    function createIssue () {
      // Setting issue string value
      issue.value = isBug.value
        ? `### Operating environment (运行环境)
${formData.form.systemPlatform}

### System Architecture (系统架构)
${formData.form.systemArch}

### Expected results (期望的结果)
${formData.form.expected}

### Actual results (实际的结果)
${formData.form.actual}

### Remarks (补充说明)
${formData.form.remarks}
`.trim()
        : `### This function solves the problem (这个功能解决的问题)
${formData.form.functionContent}`.trim()

      // Setting issue render function value
      issueRenderRef.value = isBug.value
        ? () => [
            h(NH3, null, {
              default: () => 'Operating environment (运行环境)',
            }),
            h(NAlert, { showIcon: false }, {
              default: () => formData.form.systemPlatform,
            }),

            h(NH3, null, {
              default: () => 'System Architecture (系统架构)',
            }),
            h(NAlert, { showIcon: false }, {
              default: () => formData.form.systemArch,
            }),

            h(NH3, null, { default: () => 'Expected results (期望的结果)' }),
            h(NAlert, { showIcon: false }, {
              default: () => formData.form.expected,
            }),

            h(NH3, null, { default: () => 'Actual results (实际的结果)' }),
            h(NAlert, { showIcon: false }, {
              default: () => formData.form.actual,
            }),

            h(NH3, null, { default: () => 'Remarks (补充说明)' }),
            h(NAlert, { showIcon: false }, {
              default: () => formData.form.remarks || 'Null (无)',
            }),
          ]
        : () => [
            h(NH3, null, { default: () => 'This function solves the problem (这个功能解决的问题)' }),
            h(NAlert, { showIcon: false }, {
              default: () => formData.form.functionContent,
            }),
          ]

      previewVisible.value = true
    }

    function handlePreview () {
      formRef.value.validate((errors: Array<{ message: string }[]>) => {
        if (!errors) {
          createIssue()
        } else {
          errors.forEach((item) => {
            message.error(item[0].message)
          })
          return false
        }
      })
    }

    function create () {
      const issueString = `${createComment(formData.form.type)}\n\n${issue.value
        }\n\n${createComment(formData.form.type)}`
      const issueUriComponent = encodeURIComponent(issueString).replace(
        /%2B/gi,
        '+',
      )
      window.open(
        `https://github.com/${formData.form.repo}/issues/new?title=${formData.form.title}&body=${issueUriComponent}`,
      )
    }

    watch(lang, () => {
      formRef.value.restoreValidation && formRef.value.restoreValidation()
    })

    return {
      ...toRefs(formData),
      contentText,
      issueTypeOptions,
      formRef,
      rules,
      tipVisible,
      isBug,
      previewVisible,
      issueVNode: issueRenderRef,
      autosizeConfig: {
        minRows: 3,
      },
      handlePreview,
      create,
    }
  },
})
</script>

<style scoped>
.card {
  margin-bottom: 24px;
}

.form {
  margin-top: 10px;
}

.m-b-24 {
  margin-bottom: 24px;
}

.preview {
  width: 100%;
  display: block;
  justify-content: center;
}

.preview-content {
  word-wrap: break-word;
  word-break: normal;
  overflow: hidden;
}

.preview-footer {
  width: 100%;
  display: flex;
  justify-content: center;
  margin-top: 2em;
}
</style>
